# Generated by Django 4.1.1 on 2022-09-27 17:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=29, null=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('artist_name', models.CharField(blank=True, max_length=29, null=True)),
                ('annotation', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=utils.saveAudioImage, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('audio', models.FileField(blank=True, null=True, upload_to=utils.saveAudioFile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'acc'])])),
                ('streamed', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audios', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audios', to='meta.language')),
            ],
        ),
        migrations.CreateModel(
            name='TagedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('audios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atags', to='audio.audios')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taudios', to='meta.genre')),
            ],
        ),
        migrations.CreateModel(
            name='MoodedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('audios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amoods', to='audio.audios')),
                ('moods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maudios', to='meta.moods')),
            ],
        ),
        migrations.CreateModel(
            name='GenredAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('audios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenres', to='audio.audios')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaudios', to='meta.genre')),
            ],
        ),
        migrations.CreateModel(
            name='AudiosCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caudio', to='meta.country')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acountry', to='audio.audios')),
            ],
        ),
    ]
