# Generated by Django 4.1.1 on 2022-09-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioscountry',
            old_name='Country',
            new_name='country',
        ),
    ]
