# Generated by Django 4.1.1 on 2022-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_alter_tagedaudio_tag_podcasts_playlists_episodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audios',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
