# Generated by Django 4.1.1 on 2022-09-28 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0001_initial'),
        ('audio', '0004_audios_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('playlists', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tagedplaylst', to='audio.playlists')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagedplaylists', to='meta.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('podcasts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribedusers', to='audio.podcasts')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='podcastsubscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
