# Generated by Django 4.1.1 on 2022-09-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        ('audio', '0006_tagedpodcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='annotation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='podcast_creator',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
        migrations.CreateModel(
            name='TagedEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('episodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodestag', to='audio.podcasts')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagedepisodes', to='meta.tag')),
            ],
        ),
    ]
