# Generated by Django 4.1.1 on 2022-09-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_episodes_annotation_podcasts_podcast_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episodes',
            name='streamed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
