# Generated by Django 4.1.1 on 2022-11-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_podcasts_likes_alter_tagedepisodes_episodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audios',
            name='artist_name',
        ),
    ]
