# Generated by Django 4.1.1 on 2022-11-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
